#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "86ff1600269f4f918f6e9fa9e879a630" }
]

[assets]
directory = "./public"
